using AiDevTeam.Core.Models.Workflow;

namespace AiDevTeam.Core.Interfaces;

/// <summary>
/// The deterministic workflow engine that drives task execution.
/// Uses code-based rules — NOT AI — to decide workflow transitions.
/// </summary>
public interface IWorkflowEngine
{
    Task<WorkflowExecution> StartWorkflowAsync(string conversationId, CancellationToken ct = default);
    Task<WorkflowExecution> ContinueWorkflowAsync(string conversationId, string? userInput = null, CancellationToken ct = default);
    Task<WorkflowExecution> SelectOptionAsync(string conversationId, int optionNumber, CancellationToken ct = default);
    Task<WorkflowExecution> RetryStepAsync(string conversationId, CancellationToken ct = default);
    Task<WorkflowExecution?> GetExecutionAsync(string conversationId);
    Task CancelWorkflowAsync(string conversationId);

    /// <summary>Raised when a chat message should be posted to the conversation.</summary>
    event Func<string, WorkflowChatMessage, Task>? OnChatMessage;

    /// <summary>Raised when workflow state changes.</summary>
    event Func<string, WorkflowState, Task>? OnStateChanged;
}

/// <summary>
/// A chat message generated by the workflow engine for display in the conversation.
/// Human-readable layer on top of structured JSON communication.
/// </summary>
public class WorkflowChatMessage
{
    public string Sender { get; set; } = string.Empty;
    public string SenderRole { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public string MessageType { get; set; } = string.Empty;
    public string? DetailedContext { get; set; }
    public string? DetailedContextLabel { get; set; }
}
